<?php

function role_inheritance_entity_type_build(array &$entity_types) {
  /**
   * Override entity storage class for user_role to allow for role inheritance
   * during priv validation
   */
  
  $entity_types['user_role']->setStorageClass('Drupal\role_inheritance\RoleInheritanceStorage');
}

/**
 * Helper Function for RoleInheritanceStorage class to extend based in inheritance
 */
function _role_inheritance_extendroles($rids){
    
    return $rids;
}

